<?php

namespace App\Utilities\StateSwitch;

use App\Entity\QueueTask;
use App\Utilities\Enum\QueueTaskStatusEnum;

class QueueTaskStateSwitch extends AbstractStateSwitch
{
   public function canSwitchState(int $currentState, int $newState, array $relations = QueueTaskStatusEnum::RELATIONS): bool
   {
       return parent::canSwitchState($currentState, $newState, $relations); // TODO: Change the autogenerated stub
   }
}